#!/usr/bin/env python3
"""
generate-landing-templates.py

Из tmp/landings/{office,pent,commercial}/index.html генерирует
Wolf CMS-templates assets/pages/landing-{office,pent,commercial}.phtml

Делает:
  - вытаскивает <link rel="stylesheet"> из <head>
  - вытаскивает <body>...EOF (всё содержимое после <body>)
  - вырезает <div class="menu_frame">...</div> блок (костыль-меню)
  - вырезает <!-- Yandex.Metrika --> и <!-- /Yandex.Metrika -->
    (счётчик уже на основном сайте)
  - переписывает относительные пути ассетов:
      src="./imgs/x.jpg"   → src="/promo/<name>/imgs/x.jpg"
      href="css/style.css" → href="/promo/<name>/css/style.css"
      action="callback.php" → action="/promo/<name>/callback.php"
"""

import re, os, sys

ROOT = os.path.dirname(os.path.abspath(__file__))
LANDINGS_DIR = os.path.join(ROOT, "tmp", "landings")
OUT_DIR = os.path.join(ROOT, "tmp", "templates")
os.makedirs(OUT_DIR, exist_ok=True)

NAMES = ['office', 'pent', 'commercial']

def find_balanced_div_end(text, start):
    """Find the position right after the </div> that balances <div ...> at start."""
    i = start
    depth = 0
    open_div = re.compile(r'<div\b[^>]*>', re.IGNORECASE)
    close_div = re.compile(r'</div>', re.IGNORECASE)
    while i < len(text):
        next_open = open_div.search(text, i)
        next_close = close_div.search(text, i)
        if not next_close:
            return -1
        if next_open and next_open.start() < next_close.start():
            depth += 1
            i = next_open.end()
        else:
            depth -= 1
            i = next_close.end()
            if depth == 0:
                return i
    return -1

def strip_menu_frame(body):
    """Remove the <div class="menu_frame" ...>...</div> block including its nested children."""
    pat = re.compile(r'<div\b[^>]*class\s*=\s*["\'][^"\']*menu_frame[^"\']*["\'][^>]*>', re.IGNORECASE)
    m = pat.search(body)
    if not m:
        return body
    end = find_balanced_div_end(body, m.end())
    if end == -1:
        return body
    # also strip surrounding <!--БОКОВОЕ МЕНЮ--> comments if present
    head = body[:m.start()]
    tail = body[end:]
    head = re.sub(r'<!--\s*БОКОВОЕ МЕНЮ\s*-->\s*$', '', head, flags=re.IGNORECASE)
    tail = re.sub(r'^\s*<!--\s*КОНЕЦ\s+БОКОВОЕ\s+МЕНЮ\s*-->', '', tail, flags=re.IGNORECASE)
    return head + tail

def strip_yandex(body):
    """Remove Yandex.Metrika block (комментарии + script + noscript)."""
    body = re.sub(
        r'<!--\s*Yandex\.Metrika\s+counter\s*-->.*?<!--\s*/Yandex\.Metrika\s+counter\s*-->',
        '',
        body,
        flags=re.DOTALL | re.IGNORECASE
    )
    return body

def rewrite_paths(text, prefix):
    """src/href/action: relative paths → absolute prefixed paths."""
    # src="./xxx/..." or src="xxx/..." (where xxx is asset dir)
    asset_dirs = r'(?:imgs|images|css|js|fonts|video|InDocks|sounds|public)'
    text = re.sub(
        rf'((?:src|href|action|poster|data-bg|data-src)\s*=\s*["\'])(?:\./)?({asset_dirs}/)',
        rf'\1{prefix}\2',
        text
    )
    # specific files: callback.php, callback-amp.php (form actions)
    text = re.sub(
        r'((?:action)\s*=\s*["\'])(callback[\w-]*\.php)',
        rf'\1{prefix}\2',
        text
    )
    # url(./...) and url(xxx/...) inside style attrs
    text = re.sub(
        rf'(url\(["\']?)(?:\./)?({asset_dirs}/)',
        rf'\1{prefix}\2',
        text
    )
    return text

for name in NAMES:
    src_path = os.path.join(LANDINGS_DIR, name, "index.html")
    if not os.path.exists(src_path):
        print(f"SKIP: {src_path} not found", file=sys.stderr)
        continue
    with open(src_path, encoding="utf-8") as f:
        html = f.read()

    prefix = f"/promo/{name}/"

    # CSS links from head
    head_match = re.search(r'<head\b[^>]*>(.*?)</head>', html, re.DOTALL | re.IGNORECASE)
    head_html = head_match.group(1) if head_match else ""
    css_links = re.findall(
        r'<link[^>]+rel\s*=\s*["\']stylesheet["\'][^>]*>',
        head_html,
        re.IGNORECASE
    )
    css_links = [rewrite_paths(l, prefix) for l in css_links]

    # body content
    body_match = re.search(r'<body[^>]*>', html, re.IGNORECASE)
    if not body_match:
        body_html = html
    else:
        body_html = html[body_match.end():]
    # cut off </body> and </html> if present
    body_html = re.sub(r'</body>\s*</html>\s*$', '', body_html, flags=re.IGNORECASE)
    body_html = re.sub(r'</html>\s*$', '', body_html, flags=re.IGNORECASE)
    body_html = re.sub(r'</body>\s*$', '', body_html, flags=re.IGNORECASE)

    body_html = strip_menu_frame(body_html)
    body_html = strip_yandex(body_html)
    body_html = rewrite_paths(body_html, prefix)

    # build template
    template = f"""<?php
/*
 * Landing: {name}
 * Generated by generate-landing-templates.py from htdocs/promo/{name}/index.html
 * Original landing files (CSS, JS, images, fonts) remain at /promo/{name}/
 * Side menu is rendered by main site layout (assets/layout/menu.phtml).
 */
?>

{chr(10).join(css_links)}

<!-- landing body (menu_frame stripped) -->
<div class="landing landing-{name}">
{body_html}
</div>
"""
    out_path = os.path.join(OUT_DIR, f"landing-{name}.phtml")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(template)
    print(f"WROTE: {out_path}  ({len(template)} bytes)")

print("\ndone.")
